version: '3.8'

services:
  recsalmo:
    build: .
    container_name: recsalmoContainer
    volumes:
      - ./input:/input
      - ./output:/output
    command: ["python", "recsalmo.py","/input", "/output"]